In [656]:
import torch

In [657]:
print(torch.__version__)

2.10.0+cpu


In [658]:
if torch.cuda.is_available():
    print("Gpu available")
else:
    print("Gpu not available")

Gpu not available


##### Creating Tensors

In [659]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [660]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [661]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [662]:
type(torch.ones(3,4))

torch.Tensor

In [663]:
torch.rand(2,3)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [664]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [665]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [666]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [667]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [668]:
#identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [669]:
torch.full((3,3),21)

tensor([[21, 21, 21],
        [21, 21, 21],
        [21, 21, 21]])

#### Shape of Tensors

In [670]:
t = torch.rand(3,3)
t

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [671]:
t.shape

torch.Size([3, 3])

In [672]:
torch.ones_like(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##### Data types

In [673]:
t.dtype

torch.float32

In [674]:
torch.ones(3,3,dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [675]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [676]:
t.dtype

torch.float32

In [677]:
#converting dtype of t
t_int = t.to(torch.int32)
t_int

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [678]:
t_int.dtype

torch.int32

In [679]:
torch.rand_like(t_int,dtype=torch.float32)

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [680]:
torch.rand(2,2)

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [681]:
probs = torch.full((3,3),0.5)
torch.bernoulli(probs).bool()

tensor([[ True, False, False],
        [ True, False,  True],
        [ True,  True, False]])

#### Scaler Operations

In [682]:
t = torch.rand(2,2)
t

tensor([[0.7064, 0.1629],
        [0.8902, 0.5163]])

In [683]:
t+2

tensor([[2.7064, 2.1629],
        [2.8902, 2.5163]])

In [684]:
t*2

tensor([[1.4128, 0.3258],
        [1.7804, 1.0325]])

In [685]:
t/2

tensor([[0.3532, 0.0814],
        [0.4451, 0.2581]])

In [686]:
t = t*100
t

tensor([[70.6403, 16.2878],
        [89.0198, 51.6271]])

In [687]:
t = t // 2
t

tensor([[35.,  8.],
        [44., 25.]])

In [688]:
t % 2

tensor([[1., 0.],
        [0., 1.]])

In [689]:
t**2

tensor([[1225.,   64.],
        [1936.,  625.]])

#### Element wise operations

In [690]:
t1 = torch.randint(1,10,(2,2))
t2 = torch.randint(1,10,(2,2))

In [691]:
t1

tensor([[6, 7],
        [4, 1]])

In [692]:
t2

tensor([[7, 5],
        [4, 7]])

In [693]:
t1 + t2
t1 * t2
#like that..

tensor([[42, 35],
        [16,  7]])

In [694]:
t = torch.tensor([1.2,-2,-3,4])
t

tensor([ 1.2000, -2.0000, -3.0000,  4.0000])

In [695]:
torch.abs(t)

tensor([1.2000, 2.0000, 3.0000, 4.0000])

In [696]:
torch.negative(t)

tensor([-1.2000,  2.0000,  3.0000, -4.0000])

In [697]:
torch.round(t)

tensor([ 1., -2., -3.,  4.])

In [698]:
torch.ceil(t)

tensor([ 2., -2., -3.,  4.])

In [699]:
torch.floor(t)

tensor([ 1., -2., -3.,  4.])

In [700]:
t

tensor([ 1.2000, -2.0000, -3.0000,  4.0000])

In [701]:
torch.clamp(t,min=2,max=3)

tensor([2., 2., 2., 3.])

In [702]:
t = torch.randint(1,10,(3,3),dtype=torch.float32)
t

tensor([[2., 1., 1.],
        [4., 6., 6.],
        [6., 1., 4.]])

In [703]:
torch.sum(t)

tensor(31.)

In [704]:
#col wise
torch.sum(t,dim=0)

tensor([12.,  8., 11.])

In [705]:
#row wise
torch.sum(t,dim=1)

tensor([ 4., 16., 11.])

In [706]:
torch.mean(t)

tensor(3.4444)

In [707]:
t

tensor([[2., 1., 1.],
        [4., 6., 6.],
        [6., 1., 4.]])

In [708]:
torch.mean(t,dim=0)

tensor([4.0000, 2.6667, 3.6667])

In [709]:
torch.mean(t,dim=1)

tensor([1.3333, 5.3333, 3.6667])

In [710]:
torch.median(t)

tensor(4.)

In [711]:
torch.max(t)

tensor(6.)

In [712]:
torch.min(t)

tensor(1.)

In [713]:
#standard deviation
torch.std(t)

tensor(2.2423)

In [714]:
torch.prod(t)

tensor(6912.)

In [715]:
#variance
torch.var(t)

tensor(5.0278)

In [716]:
t

tensor([[2., 1., 1.],
        [4., 6., 6.],
        [6., 1., 4.]])

In [717]:
torch.argmax(t)

tensor(4)

In [718]:
t1

tensor([[6, 7],
        [4, 1]])

In [719]:
t2

tensor([[7, 5],
        [4, 7]])

In [720]:
torch.matmul(t1,t2)

tensor([[70, 79],
        [32, 27]])

In [721]:
t3 = torch.tensor([1,2])
t4 = torch.tensor([1,2])

In [722]:
torch.dot(t3,t4)

tensor(5)

In [723]:
t1

tensor([[6, 7],
        [4, 1]])

In [724]:
t1 = torch.randint(0,10,(3,2))

In [725]:
t1

tensor([[6, 1],
        [5, 5],
        [0, 4]])

In [726]:
torch.transpose(t1,0,1)

tensor([[6, 5, 0],
        [1, 5, 4]])

In [727]:
t

tensor([[2., 1., 1.],
        [4., 6., 6.],
        [6., 1., 4.]])

In [728]:
#determinant
torch.det(t)

tensor(24.)

In [729]:
t

tensor([[2., 1., 1.],
        [4., 6., 6.],
        [6., 1., 4.]])

In [730]:
torch.inverse(t)

tensor([[ 0.7500, -0.1250,  0.0000],
        [ 0.8333,  0.0833, -0.3333],
        [-1.3333,  0.1667,  0.3333]])

In [731]:
t = torch.rand(3,3)
t

tensor([[0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [732]:
torch.log(t)

tensor([[-0.0858, -0.2757, -0.2516],
        [-0.4815, -1.0851, -1.5277],
        [-0.0562, -0.3403, -2.1564]])

In [733]:
torch.exp(t)

tensor([[2.5038, 2.1362, 2.1761],
        [1.8550, 1.4020, 1.2424],
        [2.5737, 2.0372, 1.1227]])

In [734]:
torch.sqrt(t)

tensor([[0.9580, 0.8712, 0.8818],
        [0.7861, 0.5813, 0.4659],
        [0.9723, 0.8435, 0.3402]])

In [735]:
torch.sigmoid(t)

tensor([[0.7146, 0.6811, 0.6851],
        [0.6497, 0.5837, 0.5540],
        [0.7202, 0.6707, 0.5289]])

In [736]:
torch.softmax(t,dim=0)

tensor([[0.3612, 0.3832, 0.4792],
        [0.2676, 0.2515, 0.2736],
        [0.3713, 0.3654, 0.2472]])

In [737]:
torch.relu(t)

tensor([[0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

### Inplace operations

In [738]:
t1

tensor([[6, 1],
        [5, 5],
        [0, 4]])

In [739]:
t2

tensor([[7, 5],
        [4, 7]])

In [740]:
t2.add_(t2)

tensor([[14, 10],
        [ 8, 14]])