In [196]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [197]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [198]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [199]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [200]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["diagnosis"]),df["diagnosis"],test_size=0.2,random_state=42)

In [201]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [202]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: str

In [203]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [204]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [205]:
X_train

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [206]:
y_train

tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [207]:
X_train.shape

torch.Size([455, 30])

In [208]:
class Model:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights)+self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def binary_cross_entropy(self,y_train,y_pred):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,min=epsilon,max=1-epsilon)
        loss = -(y_train*torch.log(y_pred)+(1-y_train)*torch.log(y_pred)).mean()
        return loss

In [209]:
learning_rate = 0.1
epochs = 25

In [210]:
model = Model(X_train)

In [211]:
model.weights

tensor([[0.4566],
        [0.0708],
        [0.7057],
        [0.8314],
        [0.6398],
        [0.4669],
        [0.9826],
        [0.2374],
        [0.5589],
        [0.5278],
        [0.7912],
        [0.0677],
        [0.4433],
        [0.8914],
        [0.8756],
        [0.7468],
        [0.1100],
        [0.3635],
        [0.6947],
        [0.3345],
        [0.7569],
        [0.6808],
        [0.2178],
        [0.3438],
        [0.2775],
        [0.4673],
        [0.6217],
        [0.2011],
        [0.6506],
        [0.6274]], dtype=torch.float64, requires_grad=True)

In [212]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [213]:
X_train.dtype

torch.float64

In [214]:
for epoch in range(epochs):
    y_pred = model.forward(X_train)
    loss = model.binary_cross_entropy(y_train,y_pred)
    print(f"Epoch : {epoch+1} Loss : {loss.item()}")
    loss.backward()

    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()
    

Epoch : 1 Loss : 4.03443360465943
Epoch : 2 Loss : 3.78748451888044
Epoch : 3 Loss : 3.542608172595782
Epoch : 4 Loss : 3.3001298073270737
Epoch : 5 Loss : 3.060413435831933
Epoch : 6 Loss : 2.823895786216618
Epoch : 7 Loss : 2.5911244882794398
Epoch : 8 Loss : 2.362802192789466
Epoch : 9 Loss : 2.13984060233576
Epoch : 10 Loss : 1.9234229943277628
Epoch : 11 Loss : 1.7150649500887893
Epoch : 12 Loss : 1.5166513768754657
Epoch : 13 Loss : 1.330414224791558
Epoch : 14 Loss : 1.1588066451877361
Epoch : 15 Loss : 1.0042349745604993
Epoch : 16 Loss : 0.8686484208134598
Epoch : 17 Loss : 0.7530818719673756
Epoch : 18 Loss : 0.657346954580517
Epoch : 19 Loss : 0.580035650649202
Epoch : 20 Loss : 0.5188297415109799
Epoch : 21 Loss : 0.470960734319408
Epoch : 22 Loss : 0.43364379123790814
Epoch : 23 Loss : 0.4043787854592625
Epoch : 24 Loss : 0.3810970985072565
Epoch : 25 Loss : 0.36218756666821283


In [215]:
with torch.no_grad():
    y_pred = model.forward(X_test)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == y_test).float().mean()
    print(f"Accuracy : {accuracy}")

Accuracy : 0.4030470848083496
