In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.hidden = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.output = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.hidden(features)
        out = self.sigmoid(out)
        out = self.output(out)
        out = self.sigmoid(out)
        return out


In [3]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.3087],
        [0.3077],
        [0.3080],
        [0.3064],
        [0.3034],
        [0.2998],
        [0.3117],
        [0.3010],
        [0.3033],
        [0.2983]], grad_fn=<SigmoidBackward0>)

In [8]:
model.hidden.weight

Parameter containing:
tensor([[ 0.2159,  0.3446,  0.0156, -0.3780, -0.3326],
        [ 0.0775,  0.0366, -0.2843,  0.1431, -0.3144],
        [-0.2949, -0.1314,  0.3502,  0.3583,  0.0822]], requires_grad=True)

In [4]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─Sigmoid: 1-2                           [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Sequential Container

In [12]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self,features):
        out = self.network(features)
        return out


In [13]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.5093],
        [0.5102],
        [0.5477],
        [0.5071],
        [0.5099],
        [0.5087],
        [0.5078],
        [0.5061],
        [0.5060],
        [0.5093]], grad_fn=<SigmoidBackward0>)

In [14]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00