In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [4]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["diagnosis"]),df["diagnosis"],test_size=0.2,random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: str

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [10]:
X_train

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [11]:
y_train

tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [12]:
X_train.shape

torch.Size([455, 30])

In [13]:
class Model:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights)+self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def binary_cross_entropy(self,y_train,y_pred):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,min=epsilon,max=1-epsilon)
        loss = -(y_train*torch.log(y_pred)+(1-y_train)*torch.log(y_pred)).mean()
        return loss

In [14]:
learning_rate = 0.1
epochs = 25

In [15]:
model = Model(X_train)

In [16]:
model.weights

tensor([[0.7473],
        [0.8282],
        [0.5047],
        [0.8960],
        [0.0596],
        [0.4974],
        [0.2092],
        [0.1448],
        [0.1983],
        [0.4351],
        [0.9518],
        [0.0949],
        [0.1073],
        [0.0633],
        [0.6659],
        [0.9819],
        [0.1438],
        [0.1923],
        [0.6858],
        [0.6150],
        [0.2128],
        [0.7142],
        [0.4673],
        [0.2461],
        [0.3343],
        [0.4733],
        [0.8898],
        [0.3857],
        [0.4693],
        [0.8886]], dtype=torch.float64, requires_grad=True)

In [17]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [18]:
X_train.dtype

torch.float64

In [19]:
for epoch in range(epochs):
    y_pred = model.forward(X_train)
    loss = model.binary_cross_entropy(y_train,y_pred)
    print(f"Epoch : {epoch+1} Loss : {loss.item()}")
    loss.backward()

    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()
    

Epoch : 1 Loss : 3.5878849870817633
Epoch : 2 Loss : 3.3465619379392395
Epoch : 3 Loss : 3.1079907019069855
Epoch : 4 Loss : 2.8727329748927346
Epoch : 5 Loss : 2.64144891011871
Epoch : 6 Loss : 2.414935990842309
Epoch : 7 Loss : 2.1941784424536226
Epoch : 8 Loss : 1.9803907643479195
Epoch : 9 Loss : 1.7750460067743121
Epoch : 10 Loss : 1.5798825369446572
Epoch : 11 Loss : 1.3968711303298873
Epoch : 12 Loss : 1.2281070425327798
Epoch : 13 Loss : 1.0755944409634177
Epoch : 14 Loss : 0.9409390043737077
Epoch : 15 Loss : 0.8250391452558234
Epoch : 16 Loss : 0.7278798014150676
Epoch : 17 Loss : 0.6484753184940053
Epoch : 18 Loss : 0.5849759314152986
Epoch : 19 Loss : 0.5349318574896967
Epoch : 20 Loss : 0.4956522736569544
Epoch : 21 Loss : 0.46456015432213843
Epoch : 22 Loss : 0.4394553459562231
Epoch : 23 Loss : 0.4186335172015354
Epoch : 24 Loss : 0.40086890928654795
Epoch : 25 Loss : 0.3853210178447906


In [20]:
with torch.no_grad():
    y_pred = model.forward(X_test)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == y_test).float().mean()
    print(f"Accuracy : {accuracy}")

Accuracy : 0.42028316855430603
